-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Gamemaster CASCADE;
DROP TABLE IF EXISTS Creature CASCADE;
DROP TABLE IF EXISTS Name CASCADE;
DROP TABLE IF EXISTS CreatureClass CASCADE;
DROP TABLE IF EXISTS Race CASCADE;
DROP TABLE IF EXISTS Weapon CASCADE;